---
title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Peer-reviewed Papers in English Journals

<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>

<ol reversed>

#### In press/Preprint
<div class = "row">
<div class = "col-md-10">
<li> Zhang, B., Jiang, Y., ..., Chu, C.  Elevational gradients do not significantly alter soil microbial respiration and temperature sensitivity in a subtropical forest. __Preprint__ [doi:10.22541/au.167239275.59175308/v1](https://doi.org/10.22541/au.167239275.59175308/v1)
</div>
<div class = "col-md-2">
<div data-doi="10.22541/au.167239275.59175308/v1" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.22541/au.167239275.59175308/v1" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2024
<div class = "row">
<div class = "col-md-10">
<li> Ma, S., Chen, S., Ding, Y., He, Z., Hu, G., Liu, J., ... & Zhang, Y. What controls forest litter decomposition? A coordinated distributed teabag experiment across ten mountains. __*Ecography*__, e07339 [doi:10.1111/ecog.07339](https://doi.org/10.1111/ecog.07339)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/ecog.07339" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/ecog.07339" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> He, X., Zeng, L., ..., Yang, Y. Parental material and climate jointly determine the biomass and diversity of soil microbial communities along an elevational gradient on a subtropical karst mountain. __*Journal of Biogeography*__, in press [doi:10.1111/jbi.14814](https://doi.org/10.1111/jbi.14814)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/jbi.14814" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jbi.14814" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2023
<div class = "row">
<div class = "col-md-10">
<li> Zeng, L., He, X., Zhu, G., Zhou, L., Luo, M., Yin, X., ... & Yang, Y. Bedrock and climate jointly control microbial necromass along a subtropical elevational gradient. __*Applied Soil Ecology*__, 189:104902 [doi:10.1016/j.apsoil.2023.104902](https://doi.org/10.1016/j.apsoil.2023.104902)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.apsoil.2023.104902" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.apsoil.2023.104902" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Luo, Y., Ma, L., ..., Li, D., Liu, J., Gao, L. The diversity of mycorrhiza-associated fungi and trees shapes subtropical mountain forest ecosystem functioning. __*Journal of Biogeography*__, 50: 715-729 [doi:10.1111/jbi.14563](https://doi.org/10.1111/jbi.14563)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/jbi.14563" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jbi.14563" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Dai, Z., Zhang, J., Wang, J. The ability of bryophytes to track areas of suitable climate depends on their habitat preferences. __*Journal of Systematics and Evolution*__, 61(1):227-229 [doi:10.1111/jse.12832](https://doi.org/10.1111/jse.12832)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/jse.12832" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jse.12832" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Xing, D.`*`, **Zhang, J.**, He, F. Comment on “Interspecific competition limits bird species' ranges in tropical mountains.” __*Science*__, 379(6630), eade2109 [doi:10.1126/science.ade2109](https://doi.org/10.1126/science.ade2109)
</div>
<div class = "col-md-2">
<div data-doi="10.1126/science.ade2109" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1126/science.ade2109" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2022
<div class = "row">
<div class = "col-md-10">
<li> Luo, Y., Cadotte, M.W., Liu, J., Burgess, K.S., Tan, S., Ye, L., Zou, J., Chen, Z., Jiang, X., Li, J., Xu, K., Li, D., Gao, L. Multitrophic diversity and biotic associations influence subalpine forest ecosystem multifunctionality. __*Ecology*__, 103(9):e3745 [doi:10.1002/ecy.3745](https://doi.org/10.1002/ecy.3745)
</div>
<div class = "col-md-2">
<div data-doi="10.1002/ecy.3745" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1002/ecy.3745" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Wang, X., Zhong, M.,  Yang, S., Jiang, J., Hu, J.`*` Multiple β‐diversity patterns and the underlying mechanisms across amphibian communities along a subtropical elevational gradient. __*Diversity and Distributions*__, 28: 2489-2502 [doi:10.1111/ddi.13618](https://doi.org/10.1111/ddi.13618)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/ddi.13618" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/ddi.13618" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Wang, X., Zhong, M., Zhang, J., Si, X., Yang, S., Jiang, J., Hu, J.`*` Multidimensional amphibian diversity and community structure along a 2600 m elevational gradient on the eastern margin of the Qinghai-Tibetan Plateau. __*Zoological Research*__ 43(1): 40-51 [doi:10.24272/j.issn.2095-8137.2021.166](https://doi.org/10.24272/j.issn.2095-8137.2021.166)
</div>
<div class = "col-md-2">
<div data-doi="10.24272/j.issn.2095-8137.2021.166" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.24272/j.issn.2095-8137.2021.166" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li>Zhu, G., Zhou, L., He, X., Wei, P., Lin, D., Qian, S., ... & Yang, Y.`*` Effects of elevation gradient on soil carbon and nitrogen in a typical karst region of Chongqing, southwest China. __*Journal of Geophysical Research: Biogeosciences*__ 127(6): e2021JG006742 [doi:10.1029/2021JG006742](https://doi.org/10.1029/2021JG006742)
</div>
<div class = "col-md-2">
<div data-doi="10.1029/2021JG006742" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1029/2021JG006742" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Ma, L., Liu, L., Lu, Y., Chen, L., Zhang, Z., Zhang, H., Wang, X., Shu, L., Yang, Q., Song, Q., Peng, Q., Yu, Z., Zhang, J.`*` When microclimates meet soil microbes: soil temperature mediates soil microbial diversity along an elevational gradient in subtropical forests. __*Soil Biology and Biochemistry*__ 166: 108566 [doi:10.1016/j.soilbio.2022.108566](https://doi.org/10.1016/j.soilbio.2022.108566)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.soilbio.2022.108566" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.soilbio.2022.108566" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Chen, B., Chen, L., Jiang, L., ..., He, Z.`*` C:N:P Stoichiometry of Plant, Litter and Soil along an Elevational Gradient in Subtropical Forests of China. __*Forests*__, 13: 372 [doi:10.3390/f13030372](https://doi.org/10.3390/f13030372)
</div>
<div class = "col-md-2">
<div data-doi="10.3390/f13030372" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.3390/f13030372" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Yang, X., Angert, A.L., Zuidema, P.A., He, F., Huang, S., Li, S.Z., Li, S.L., Chardon, N.I.,  Zhang, J.`*` The role of demographic compensation in stabilizing marginal tree populations in North America. __*Ecology Letters*__, 25(7): 1676-1689 [doi:10.1111/ELE.14028](https://doi.org/10.1111/ELE.14028)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/ELE.14028" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/ELE.14028" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Lembrechts, J., van den Hoogen, J., Aalto, A., …, **Zhang, J.**, **Zhang, Z.C.**, …, Lenoir, J.`*`. Global maps of soil temperature. __*Global Chang Biology*__, 28(9): 3110-3144  [doi:10.1111/gcb.16060](https://doi.org/10.1111/gcb.16060) [Data available here: https://zenodo.org/record/4558732#.YgsdeuhByUm]
</div>
<div class = "col-md-2">
<div data-doi="10.1111/gcb.16060" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/gcb.16060" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Zhang, XJ, Wu, D, Li, QY, Pu, FG, Xia, XL, Chang, MY, Song, K.`*`. Influence of Colder Temperature on the Axial and Radial Parenchyma Fraction of *Quercus ciliaris* C.C.Huang & Y.T.Chang Wood and Its Relationship with Carbohydrate Reserve (NSC). __*Forests*__, 13(2): 169  [doi:10.3390/f13020169](https://doi.org/10.3390/f13020169)
</div>
<div class = "col-md-2">
<div data-doi="10.3390/f13020169" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.3390/f13020169" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2021
<div class = "row">
<div class = "col-md-10">
<li> He, X., Chu, C., Yang, Y., Shu, Z., Li, B., Hou, E. Bedrock and climate jointly control the phosphorus status of subtropical forests along two elevational gradients. __*Catena*__, 206: 105525 [doi:10.1016/j.catena.2021.105525](https://doi.org/10.1016/j.catena.2021.105525)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.catena.2021.105525" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.catena.2021.105525" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Zhang, R., **Zhang, Z.**, Shang, K., Zhao, M., ..., **Zhang, J.**`*` A taxonomic and phylogenetic perspective on plant community assembly along an elevational gradient in subtropical forests. __*Journal of Plant Ecology*__, 14(4): rtab026 [doi:10.1093/jpe/rtab026](https://doi.org/10.1093/jpe/rtab026)
</div>
<div class = "col-md-2">
<div data-doi="10.1093/jpe/rtab026" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1093/jpe/rtab026" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Ding, Y., Zang, R. Determinants of aboveground biomass in forests across three climatic zones in China. __*Forest Ecology and Management*__, 482: 118805  [doi:10.1016/j.foreco.2020.118805](https://doi.org/10.1016/j.foreco.2020.118805)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.foreco.2020.118805" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.foreco.2020.118805" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> He, X., Augusto, L., Goll, D. S., Ringeval, B., Wang, Y., Helfenstein, J., Huang, Y., Yu, K., Wang, Z., Yang, Y., and Hou, E. Global patterns and drivers of soil total phosphorus concentration. __*Earth System Science Data*__, 13: 5831–5846  [doi:10.5194/essd-13-5831-2021](https://doi.org/10.5194/essd-13-5831-2021)
</div>
<div class = "col-md-2">
<div data-doi="10.5194/essd-13-5831-2021" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.5194/essd-13-5831-2021" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Jensen, D.A., Rao, M.D., **Zhang, J.**, Gron, M., Tian, S., Ma, K.P., Svenning, J-C. The potential for using rare, native species in reforestation– A case study of yews (Taxaceae) in China. __*Forest Ecology and Management*__ 482:118816 [doi:10.1016/j.foreco.2020.118816](https://doi.org/10.1016/j.foreco.2020.118816)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.foreco.2020.118816" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.foreco.2020.118816" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2020

<div class = "row">
<div class = "col-md-10">
<li> **He, X.**, Hou, E., Veen, G.F., Ellwood, M., Dijkstra, P., Sui, X., Zhang, S., Wen, D. and **Chu, C.** Soil microbial biomass increases along elevational gradients in the tropics and subtropics but not elsewhere. __*Global Ecology and Biogeography*__ 29(2):345-354. [doi:10.1111/geb.13017](https://doi.org/10.1111/geb.13017)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/geb.13017" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/geb.13017" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> **Wang, X.**, Yang, S., Guo, C., Tang, K., Jiang, J. and **Hu, J.**`*` [Amphibian diversity and conservation along an elevational gradient on Mount Emei, southwestern China](http://amphibian-reptile-conservation.org/pdfs/Volume/Vol_14_no_3/ARC_14_3_[General_Section]_46-56_e252.pdf). __*Amphibian & Reptile Conservation*__ 14(3):46-56.
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> **Liu, L.**, Zhu, K., Wurzburger, N. and **Zhang, J.** Relationships between plant and soil microbial diversity vary across taxonomic groups and spatial scales. __*Ecosphere*__ 11(1):e02999 [doi:10.1002/ecs2.2999](https://doi.org/10.1002/ecs2.2999)
</div>
<div class = "col-md-2">
<div data-doi="10.1002/ecs2.2999" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1002/ecs2.2999" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Qian, H., **Zhang, J.**, Sandel, B. and Jin, Y. 2020. Phylogenetic structure of angiosperm trees in local forest communities along latitudinal and elevational gradients in eastern North America. __*Ecography*__ 43:419–430 [doi:10.1111/ecog.04873](https://doi.org/10.1111/ecog.04873)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/ecog.04873" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/ecog.04873" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Lembrechts, J., Aalto, J., Ashcroft, M., …, **Zhang, J.**, **Zhang, Z.C.**, et al. SoilTemp: a global database of near-surface temperature. __*Global Chang Biology*__ 26(11): 6616–6629 [doi:10.1111/gcb.15123](https://doi.org/10.1111/gcb.15123)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/gcb.15123" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/gcb.15123" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Zhang, X., Song, K., Pan, YJ, Gao, ZW, Pu, FG, Lu, JH, Shang, KK, Da, L., Ellen, C. Responses of leaf traits to low temperature in an evergreen oak at its upper limit. __*Ecological Research*__ 35: 900–911 [doi:10.1111/1440-1703.12157](https://doi.org/10.1111/1440-1703.12157)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/1440-1703.12157" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/1440-1703.12157" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### 2019
<div class = "row">
<div class = "col-md-10">
<li> **Luo, Y.**, Cadotte, M.W., Burgess, K.S., **Liu, J.**, Tan, S., Zou, J., Xu, K., Li, D. and Gao, L. Greater than the sum of the parts: how the species composition in different forest strata inﬂuence ecosystem function. __*Ecology Letters*__ 22(9):1449-1461. [10.1111/ele.13330](https://doi.org/10.1111/ele.13330)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/ele.13330" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/ele.13330" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> **Luo, Y.**, Cadotte, M.W., Burgess, K.S., **Liu, J.**, Tan, S., Xu, K., Li, D. and Gao, L. Forest community assembly is driven by different strata‐dependent mechanisms along an elevational gradient. __*Journal of Biogeography*__ 46(10):2174-2187. [10.1111/jbi.13669](https://doi.org/10.1111/jbi.13669)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/jbi.13669" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jbi.13669" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Jiang, L., **He, Z.**, Liu, J., Xing, C., Gu. X., Wei, C., Zhu, J. and Wang, X. Elevation Gradient Altered Soil C, N, and P Stoichiometry of *Pinus taiwanensis* Forest on Daiyun Mountain. __*Forests*__ 10:1089. [10.3390/f10121089](https://doi.org/10.3390/f10121089)
</div>
<div class = "col-md-2">
<div data-doi="10.3390/f10121089" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.3390/f10121089" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Dai, Z., Tang, X., Tu, S., Zhuang, L., Zhu, M., Zhao, M., **Zhang, Z.** and **Wang, J.** *Cololejeunea tianmuensis*, a new epiphyllous species of *Cololejeunea* (Lejeuneaceae, Marchantiophyta) from Zhejiang, China. __*Phytotaxa*__ 402(1):057-062. [10.11646/phytotaxa.402.1.8](https://doi.org/10.11646/phytotaxa.402.1.8)
</div>
<div class = "col-md-2">
<div data-doi="10.11646/phytotaxa.402.1.8" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.11646/phytotaxa.402.1.8" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Ding, Y., Zang, R., Lu, X., Huang, J., Xu, Y. The effect of environmental filtering on variation in functional diversity along a tropical elevational gradient. __*Journal of Vegetation Science*__ 30: 973-983. [10.1111/jvs.12786](https://doi.org/10.1111/jvs.12786)
</div>
<div class = "col-md-2">
<div data-doi="10.1111/jvs.12786" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1111/jvs.12786" data-style="small_rectangle"></span>
</div>
</div>

<br>

#### Before 2019
<div class = "row">
<div class = "col-md-10">
<li> **Luo, Y.**, **Liu, J.**, Tan, S., Cadotte, M.W., Xu, K., Gao, L. and Li, D. 2016. Trait variation and functional diversity maintenance of understory herbaceous species coexisting along an elevational gradient in Yulong Mountain, Southwest China. __*Plant Diversity*__ 38(6):303-311. [10.1016/j.pld.2016.11.002](https://doi.org/10.1016/j.pld.2016.11.002)
</div>
<div class = "col-md-2">
<div data-doi="10.1016/j.pld.2016.11.002" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1016/j.pld.2016.11.002" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> Tang, X., Gradstein, S.R., Sun, L., Zhu, M., Shi, R., Wei, Q., Chen, Y., Zhou, X. and **Wang, J.** 2018. A contribution to the knowledge of epiphyllous bryophytes in Tianmushan National Nature Reserve (Zhejiang, China), with remarks on climate warming and nature conservation. __*Lindbergia*__ 402(1):057-062. [10.25227/linbg.01103](https://doi.org/10.25227/linbg.01103)
</div>
<div class = "col-md-2">
<div data-doi="10.25227/linbg.01103" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.25227/linbg.01103" data-style="small_rectangle"></span>
</div>
</div>

<div class = "row">
<div class = "col-md-10">
<li> **Luo, Y.**, **Liu, J.**, Tan, S., Cadotte, M.W., Wang, Y., Xu, K., Li, D. and Gao, L. 2016. Trait-Based Community Assembly along an Elevational Gradient in Subalpine Forests: Quantifying the Roles of Environmental Factors in Inter- and Intraspecific Variability. __*PLoS ONE*__ 11(5):e0155749. [10.1371/journal.pone.0155749](https://doi.org/10.1371/journal.pone.0155749)
</div>
<div class = "col-md-2">
<div data-doi="10.1371/journal.pone.0155749" data-hide-no-mentions="true" class="altmetric-embed"></div>
<span class="__dimensions_badge_embed__" data-doi="10.1371/journal.pone.0155749" data-style="small_rectangle"></span>
</div>
</div>

<hr>

### Peer-reviewed Papers in Chinese Journals

<ol reversed>
<li> He, Z. et al. 2022. Characteristics of microbial functional diversity and its influencing factors of forest soils at different elevations on the southern slope of Daiyun Mountain. 戴云山南坡不同海拔森林土壤微生物功能多样性特征及影响因素. __*Acta Ecologica Sinica 生态学报*__ 42(9): 3504-3515. (In Chinese) [doi: 10.5846/stxb202101210217](https://doi.org/10.5846/stxb202101210217) </li>
<li> He, Z. et al. 2022. Characteristics and its influencing factors of forest soil dominant bacterial community in different elevations on the southern slope of Daiyun Mountain, Fujian Province of eastern China. 戴云山南坡不同海拔森林土壤优势细菌群落特征及影响因素. __*Journal of Beijing Forestry University 北京林业大学学报*__ 44(7): 107-116. (In Chinese) [doi: 10.12171/j.1000-1522.20200278](https://doi.org/10.12171/j.1000-1522.20200278) </li>
<li> He, Z. et al. 2022. Forest soil microbial community structure characteristics and its influencing factors at different elevations on the Souther slope of Daiyuan Mountain. 戴云山南坡不同海拔森林土壤微生物群落结构特征和影响因素. __*Environmental Science 环境科学*__ 43(5): 2802-2811. (In Chinese) [doi: 10.13227/j.hjkx.202108160](https://doi.org/10.13227/j.hjkx.202108160) </li>
<li> Zhou, L., Huang, L., Qian, C., Li, L. and **Yang, Y.** 2019. Vertical Change in Air Temperature on the West Slope of Mt．Jinfo，China. 金佛山西坡气温的垂直变化特征. __*Mountain Research 山地学报*__ 37(6):818-827. (In Chinese) [doi: 10.16089/j.cnki.1008-2786.000472](https://doi.org/10.16089/j.cnki.1008-2786.000472) </li>
<li> **Zhang, J.`*`** and Huang, X.L. 2019. Biodiversity along elevational gradients: the commemoration of the 250th birthday of Alexander von Humboldt. 生物多样性的海拔梯度格局——纪念亚历山大·冯·洪堡诞辰250周年. __*WUYI Science Journal 武夷科学*__ 35(1):1–3. (In Chinese) [doi: 10.15914/j.cnki.wykx.2019.01.01](https://doi.org/10.15914/ j.cnki.wykx.2019.01.01) </li>
<li> Zhang, F.L., Wang, X., Zhang, O.K., Zhang, Z.C. and **Zhang, J.`*`** 2019. The health status of ancient trees and their variations along an altitudinal gradient in the West Tianmu Mountain, Zhejiang province. 浙江西天目山古树树干健康状况及其随海拔梯度变化规律. __*WUYI Science Journal 武夷科学*__ 35(1):12–20. (In Chinese) [doi: 10.15914/10.15914/j.cnki.wykx.2019.01.03](https://doi.org/10.15914/j.cnki.wykx.2019.01.03) </li>


</ol>

<hr>